<?php
$langues = array(
	'langue' => 'Македонски',
	'locale' => 'mk_MK',
	'addVirtual' => 'Додади VirtualHost',
	'backHome' => 'Дома',
	'VirtualSubMenuOn' => '<code>Опцијата VirtualHost sub-menu</code> мора да биде вклучена(On) во секцијата со<code>Wamp Нагодувања</code> во менито (десен клик на system tray икона). Откако ќе го направите тоа, вчитајте ја оваа страна повторно',
	'UncommentInclude' => 'Од-коментирајте <small>(отстранете го симболот #)</small> кај линијата <code>#Include conf/extra/httpd-vhosts.conf</code><br> во датотеката %s',
	'FileNotExists' => 'Датотеката <code>%s</code> не постои',
	'FileNotWritable' => 'Во датотеката <code>%s</code> не може да се запише',
	'DirNotExists' => '<code>%s</code> не постои или пак не е директориум',
	'NotCleaned' => 'Датотеката <code>%s</code> не е избришана.<br>Сеуште постојат VirtualHost примери како на пр. : dummy-host.example.com',
	'NoVirtualHost' => 'Нема дефиниран VirtualHost во <code>%s</code><br>, треба да постои барем еден VirtualHost за localhost.',
	'NoFirst' => 'Првиот VirtualHost мора да биде дефиниран како <code>localhost</code> во датотеката <code>%s</code>',
	'ServerNameInvalid' => 'ServerName <code>%s</code> е невалиден стринг.',
	'VirtualHostName' => 'Името на <code>Virtual Host</code> не смее да има невалидни симболи (éçëñ), празни места( ) или пак долна линија(_)',
	'VirtualHostFolder' => 'Целосна апсолутна <code>патека</code> на <code>директориумот</code> со VirtualHost <i>Пример: C:/wamp/www/projet/ or E:/www/site1/</i>',
	'VirtualAlreadyExist' => 'ServerName <code>%s</code> веќе постои',
	'Start' => 'Се креира VirtualHost (Може да трае подолго време...)',
	'GreenErrors' => 'Грешките обележани со зелена боја и рамка може да се корегираат автоматски.',
	'Correct' => 'Почни автоматско корегирање на грешките обележани со зелена боја',
	'NoModify' => 'Не е возможна модификација на датотеките <code>httpd-vhosts.conf</code> или <code>hosts</code>',
	'VirtualCreated' => 'Датотеките се модифицирани. Virtual host <code>%s</code> е успешно креиран',
	'CommandMessage' => 'Порака од конзола, треба да се смени DNS:',
	'However' => 'Можете да додате уште еден VirtualHost со опцијата "Add a VirtualHost".<br>Меѓутоа, за да биде активен овој VirtualHost во рамките на Apache, мора да ја одберете опцијата<br><code>Restart DNS</code><br>од менито со алатки (десен клик). <i>(Оваа постапка не може да се модифицира)</i>',
);
?>
