<?php
$langues = array(
	'langue' => 'Português',
	'locale' => 'brazil',
	'addVirtual' => 'Adicionar VirtualHost',
	'backHome' => 'Voltar ao Início',
	'VirtualSubMenuOn' => 'O <code>sub-menu VirtualHost</code> devem ser ativado no menu do botão direito <code>Opções do Wamp</code> <br> Ative este item e recarregue esta página',
	'UncommentInclude' => 'Descomente <small>(Apague #)</small> na linha <code>#Include conf/extra/httpd-vhosts.conf</code><br>no Arquivo %s',
	'FileNotExists' => 'O Arquivo <code>%s</code> não existe',
	'FileNotWritable' => 'The file <code>%s</code> is not writable',
	'FileNotWritable' => 'O Arquivo <code>%s</code> não é gravável',
	'DirNotExists' => '<code>%s</code> não existe ou não é um diretório',
	'NotCleaned' => 'O arquivo <code>%s</code> não foi entendido. Siga os exemplos de VirtualHost como: dummy-host.example.com',
	'NoVirtualHost' => 'Não há VirtualHost definida em <code>%s</code><br> Ele deve ter pelo menos o VirtualHost para localhost.',		'NoFirst' => 'The first VirtualHost must be <code>localhost</code> in <code>%s</code> file',
	'ServerNameInvalid' => 'O ServerName <code>%s</code> é Inválido.',
	'VirtualHostName' => 'Digite o Nome do <code>Virtual Host</code> Sem characteres especiais (éçëñ) - Sem espaços - Sem underscore(_)',
	'VirtualHostFolder' => 'Digite o <code>path</code> Caminho Completo do <code>Diretorio</code> do VirtualHost. <i>Exemplos: C:/wamp/www/projet/ ou E:/www/site1/</i>',
	'VirtualAlreadyExist' => 'O ServerName <code>%s</code> já existe.',
	'VirtualHostExists' => 'VirtualHost já definidos:',
	'Start' => 'Iniciar a criação do VirtualHost (Pode demorar um pouco ...)',
	'GreenErrors' => 'Os erros verdes verificados podem ser corrigidos automaticamente.',
	'Correct' => 'Start the automatic correction of errors inside the green borders panel',
	'Correct' => 'Comece a correção automática de erros dentro da aba verde do painel',
	'NoModify' => 'Impossível modificar o arquivo <code>httpd-vhosts.conf</code> ou <code>hosts</code>',
	'VirtualCreated' => 'Os arquivos foram modificados. o Virtual host <code>%s</code> foi criada',
	'CommandMessage' => 'As mensagens do console para atualizar o DNS:',
	'However' => 'Você pode adicionar outro VirtualHost em "Adicionar um VirtualHost". <br> No entanto, para estes novos VirtualHost feitos por conta do Apache, você deve executar o comando <br><code>Restart DNS</code><br> Clique direito no ícone do Wamp e no menu Ferramentas. <i>(Isto pode, infelizmente, não ser feito automaticamente) </i> ',
	);
?>
