<?php
$langues = array(
	'langue' => 'Македонски',
	'locale' => 'mk_MK',
	'titreHtml' => 'WAMPSERVER почетна страна',
	'titreConf' => 'Конфигурација на серверот',
	'versa' => 'Apache Верзија:',
	'doca2.2' => 'httpd.apache.org/docs/2.2/en/',
	'doca2.4' => 'httpd.apache.org/docs/2.4/en/',
	'versp' => 'PHP Верзија:',
	'server' => 'Server Software:',
	'docp' => 'www.php.net/manual/en/',
	'versm' => 'MySQL Верзија:',
	'docm' => 'dev.mysql.com/doc/index.html',
	'phpExt' => 'Вчитани екстензии : ',
	'titrePage' => 'Алатки',
	'txtProjet' => 'Мои Проекти',
	'txtNoProjet' => 'Сеуште нема проекти.<br />За да креирате нов проект, направете директориум во \'www\'.',
	'txtAlias' => 'Мои Aliases',
	'txtNoAlias' => 'Сеуште нема  Alias.<br />За да креирате нов, искористете го WAMPSERVER менито.',
	'txtVhost' => 'Мои VirtualHost',
	'txtServerName' => 'ServerName %s - има синтаксна грешка во датотеката %s',
	'txtVhostNotClean' => 'Датотеката %s не е избришана. Сеуште постојат VirtualHost примери како на пр.: dummy-host.example.com',
	'txtNoVhost' => 'Нема дефиниран VirtualHost. Додадете по една дефиниција за секој проект во: wamp/bin/apache/apache%s/conf/extra/httpd-vhosts.conf',
	'txtNoIncVhost' => 'Од-коментирајте или додадете <i>Include conf/extra/httpd-vhosts.conf</i> во : wamp/bin/apache/apache%s/conf/httpd.conf',
	'txtNoVhostFile' => 'Датотеката: %s не постои',
	'txtNoPath' => 'Патеката %s за %s не постои (датотека %s)',
	'txtNotWritable' => 'Датотеката: %s нема дозвола за запишување',
	'txtNbNotEqual' => 'Бројот на %s не е ист со бројот на %s во %s датотеката',
	'txtAddVhost' => 'Додавање на Virtual Host',
	'txtPortNumber' => 'Бројот на порта за %s нема точна вредност или не е во истата датотека за %s',
	'txtCorrected' => 'Некои VirtualHosts грешки не може да се корегираат.',
	'forum' => 'http://forum.wampserver.com/list.php?2',
	'portUsed' => 'Дефинирана порта за Apache: ',
	'mysqlportUsed' => 'Дефинирана порта за MySQL: ',
	'nolocalhost' => 'Лоша идеја: не треба да се додаде localhost во url за нов проект. Треба да се дефинира VirtualHost во <br />wamp/bin/apache/apache%s/conf/extra/httpd-vhosts.conf<br />.',
);
?>
