-- 查询所有
SELECT * FROM TABLE_NAME;


-- 选择查询
SELECT USER_NAME FROM TABLE_NAME;


-- 单条件查询
SELECT USER_NAME FROM TABLE_NAME WHERE ID<10;


-- 多条件查询（or 和 and）
SELECT USER_NAME FROM TABLE_NAME WHERE ID<5 OR ID>10;

SELECT USER_NAME FROM TABLE_NAME WHERE ID<5 AND GENDER='男';


